[package]
name = "trouble-host"
version = "0.1.0"
edition = "2021"
description = "A crate name reserved for the trouble project"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
